### ISSUE TITLE
Pinning a grpc client

### ISSUE THREAD

**Issue by yanpozka** [tam7t/hpkp#13]
Hello there, this library is super cool for me, I don't know why doesn't have more starts :(

A little question: is possible to do pinning with a grpc client ?
There's a secure client for grpc [here](https://github.com/kelseyhightower/helloworld/blob/master/secure-client/main.go), but I got lost trying to make it fit with this lib, it looks like it's possible 'cause both handle the idea of tls.Configs in some points.

Other question, are you using this library in production ? I have used it for my toy projects, but now I have intentions to use it in a real project at work.

Thanks in advance!!

**Comment by tam7t** [comment]
Thanks for the support!

I _think_ you could pass the `dialConf.NewDialer()` from the example into a [`grpc.WithDialer`](https://godoc.org/google.golang.org/grpc#WithDialer) and _then_ put that after the [`grpc.WithTransportCredentials`](https://github.com/kelseyhightower/helloworld/blob/master/secure-client/main.go#L45) of the `grpc.Dial`.

What I've done with grpc in production is to have a dedicated certificate authority and only trust the root cert, as in kelsey's example. I'm not too sure of the utility using cert pinning in that context. I was mostly thinking of using this package on forks of public service api golang libraries (like the github or digitalocean) but haven't really gotten around to that yet.

**Comment by yanpozka** [comment]
Awesome, double thanks!!! yes it looks that `WithDialer()` should work and yes it makes a more sense just trust in your own ca
